### ISSUE TITLE
执行演练报错

### ISSUE THREAD

**Issue by zhouxihong1** [chaosblade-io/chaosblade-box#61]
执行演练时报错(实际任务生效，但页面显示失败)：

3,000 milliseconds timeout on connection http-outgoing-22 [ACTIVE]

求教有可能是什么原因导致的

2021-07-28 22:39:58.673, INFO , [http-nio-8080-exec-7] c.alibaba.chaosblade.box.service.task.DefaultActivityTaskExecuteContext - 开始执行演练, 任务ID：1420393600444960770
2021-07-28 22:39:58.686, INFO , [http-nio-8080-exec-7] c.alibaba.chaosblade.box.service.task.DefaultActivityTaskExecuteContext - 开始接入监控, 任务ID：1420393600444960770
2021-07-28 22:39:58.692, INFO , [EXPERIMENT-TASK-THREAD-3] c.a.c.box.service.task.stateless.DefaultActivityTaskPhaseHandler - 检查任务状态，任务ID: 1420393600444960770，任务状态: RUNNING
2021-07-28 22:39:58.699, INFO , [EXPERIMENT-TASK-THREAD-3] c.a.c.box.service.task.stateless.DefaultActivityTaskPhaseHandler - 检查子任务状态，子任务ID: 1420393600444960770，任务状态: READY
2021-07-28 22:39:58.703, INFO , [EXPERIMENT-TASK-THREAD-3] c.a.c.box.service.task.stateless.DefaultActivityTaskPhaseHandler - 开始运行子运行，任务ID: 1420393600444960770，阶段：ATTACK, 子任务ID：1420393600486903809
2021-07-28 22:40:01.733, INFO , [EXPERIMENT-TASK-THREAD-7] c.a.c.box.service.task.stateless.DefaultActivityTaskPhaseHandler - 子任务运行中，任务ID: 1420393600444960770，阶段：ATTACK, 子任务ID: 1420393600486903809, 当前机器: 86d79a3d-2cb4-524d-b951-07982c930af3-172.28.100.68, 是否成功: false, 失败原因: 3,000 milliseconds timeout on connection http-outgoing-22 [ACTIVE]
2021-07-28 22:40:01.746, ERROR, [EXPERIMENT-TASK-THREAD-7] c.a.c.box.service.task.stateless.DefaultActivityTaskPhaseHandler - 子任务运行失败，任务ID: 1420393600444960770，阶段：ATTACK, 子任务ID: 1420393600486903809 java.util.concurrent.CompletionException: java.net.SocketTimeoutException: 3,000 milliseconds timeout on connection http-outgoing-22 [ACTIVE] at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:838) at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:811) at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) Caused by: java.net.SocketTimeoutException: 3,000 milliseconds timeout on connection http-outgoing-22 [ACTIVE] at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:387) at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:92) at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:39) at org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractIODispatch.java:175) at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIOReactor.java:263) at org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(AbstractIOReactor.java:492) at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:213) at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280) at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) ... 1 common frames omitted

**Comment by tiny-x** [comment]
应该是 CPU 满载演练导致响应的线程轮不到时间片，就显示超时了

**Comment by zhuangzhuangdashen** [comment]
应该是第一次执行prepare接口超时了，重复执行的时候会报“实验已存在”

**Comment by cyckax** [comment]
我也遇到了 我测试的是断网 实际上断网成功了 但是exclude端口没设置成功

**Comment by xcaspar** [comment]
Fixed in v1.1.0 version. https://github.com/chaosblade-io/chaosblade-box/releases/latest
