### ISSUE TITLE
com.alibaba.chaosblade.box.common.infrastructure.exception.PermissionDeniedException: null

### ISSUE THREAD

**Issue by dolphin17** [chaosblade-io/chaosblade-box#93]
2022-06-17 09:45:19.217 ERROR 18511 --- [nio-7001-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.alibaba.chaosblade.box.common.infrastructure.exception.PermissionDeniedException] with root cause

com.alibaba.chaosblade.box.common.infrastructure.exception.PermissionDeniedException: null
	at com.alibaba.chaosblade.box.auth.CloudLoginUserResolver.resolve(CloudLoginUserResolver.java:56) ~[classes!/:na]
	at com.alibaba.chaosblade.box.auth.UserWebArgumentResolver.resolveArgument(UserWebArgumentResolver.java:48) ~[classes!/:na]
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:121) ~[spring-web-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:158) ~[spring-web-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:128) ~[spring-web-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) ~[spring-webmvc-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) ~[spring-webmvc-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) ~[spring-webmvc-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]

chaosblade-box登陆的时候报这个错误是什么意思？

**Comment by dolphin17** [comment]
刚访问7001端口就这样了，登陆页一闪而过，都没办法去操作登陆

**Comment by MandssS** [comment]
那你登陆成功了嘛？如果第一次需要先注册，然后再登陆

**Comment by dolphin17** [comment]
那肯定没有了，哪里注册，有没操作文档可以跟着学的？

**Comment by MandssS** [comment]
登陆页面就有注册的入口
