### ISSUE TITLE
部署完毕后前端报500的错误，后端如下

### ISSUE THREAD

**Issue by vss80p585** [chaosblade-io/chaosblade-box#97]
2022-07-01 22:29:31.323 ERROR 17386 --- [_ClusterManager] c.a.c.b.d.s.quartz.ChaosJobStoreTX       : ClusterManager: Error managing cluster: Failure identifying failed instances when checking-in: Table 'chaosblade.t_chaos_m_quartz_SCHEDULER_STATE' doesn't exist

org.quartz.JobPersistenceException: Failure identifying failed instances when checking-in: Table 'chaosblade.t_chaos_m_quartz_SCHEDULER_STATE' doesn't exist
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.findFailedInstances(JobStoreSupport.java:3405) ~[quartz-2.3.0.jar!/:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.clusterCheckIn(JobStoreSupport.java:3455) ~[quartz-2.3.0.jar!/:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3325) ~[quartz-2.3.0.jar!/:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3920) [quartz-2.3.0.jar!/:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3957) [quartz-2.3.0.jar!/:na]
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'chaosblade.t_chaos_m_quartz_SCHEDULER_STATE' doesn't exist
	at sun.reflect.GeneratedConstructorAccessor88.newInstance(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_332]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_332]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.44.jar!/:5.1.44]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.44.jar!/:5.1.44]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943) ~[mysql-connector-java-5.1.44.jar!/:5.1.44]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973) ~[mysql-connector-java-5.1.44.jar!/:5.1.44]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909) ~[mysql-connector-java-5.1.44.jar!/:5.1.44]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527) ~[mysql-connector-java-5.1.44.jar!/:5.1.44]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680) ~[mysql-connector-java-5.1.44.jar!/:5.1.44]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487) ~[mysql-connector-java-5.1.44.jar!/:5.1.44]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858) ~[mysql-connector-java-5.1.44.jar!/:5.1.44]
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1966) ~[mysql-connector-java-5.1.44.jar!/:5.1.44]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[HikariCP-2.5.1.jar!/:na]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[HikariCP-2.5.1.jar!/:na]
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectSchedulerStateRecords(StdJDBCDelegate.java:2994) ~[quartz-2.3.0.jar!/:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.findFailedInstances(JobStoreSupport.java:3369) ~[quartz-2.3.0.jar!/:na]
	... 4 common frames omitted

**Comment by crushCoin** [comment]
> 环境是kubesphere ，helm方式及java方式启动均报同样的错误

修改mysql配置 lower_case_table_names=1

**Comment by HakunamatataLeo** [comment]
![image](https://github.com/chaosblade-io/chaosblade-box/assets/4550421/4e2328dc-e4be-4cd2-be2f-e43bf1a7d63d)
添加下环境就 ok
